version: "3.7"

services:
  backend:
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
    # volumes:
    #   - ./backend:/usr/src/app
    links:
      - db
  db:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
        MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS}"
    command: [--auth]
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb_data_container:/data/db
# volumes:
#   mongodb_data_container: